### ISSUE TITLE
Change (indeterminate to false/true) is visible only after a page refresh.

### ISSUE THREAD

**Issue by ckwane** [snyholm/indeterminatecheckbox#3]
I found a bug in the Indeterminate Checkbox:
when the status is indeterminate (value=null) and we set its value to false or true, then the change
is visible only after a page refresh.

**Comment by snyholm** [comment]
Version 2.0 has now been released and should fix this issue. Please let me know if you are still seeing it.

**Comment by ckwane** [comment]
Hi Sebastian,

Thank you. I'll test the new version and let you know if it works fine.

Best regards,
Khalid

**Comment by ckwane** [comment]
Hi,

Unfortunately, I've just tested the new version (2.0.1) and it still doesn't work. Here is the source code of the example I tested. Once the checkbox is indeterminate after clicking on the button [Set to Indeterminate] we cannot change programmatically its value anymore to false or true by clicking to the other buttons [Set to False] and [Set to True]. 

Environment used: Java 7 & Oracle WebLogic Server 12c

```
HorizontalLayout hl = new HorizontalLayout();
hl.setSpacing(true);
searchFormLayout.addComponent(hl);

final IndeterminateCheckBox checkBox = new IndeterminateCheckBox();

I18nButton falseButton = new I18nButton("Set to False");
falseButton.addClickListener(new Button.ClickListener() {
	@Override
	public void buttonClick(ClickEvent event) {
		checkBox.setValue(false);
	}
});
hl.addComponent(falseButton);

I18nButton trueButton = new I18nButton("Set to True");
trueButton.addClickListener(new Button.ClickListener() {
	@Override
	public void buttonClick(ClickEvent event) {
		checkBox.setValue(true);
	}
});
hl.addComponent(trueButton);

I18nButton indeterminateButton = new I18nButton("Set to Indeterminate");
indeterminateButton.addClickListener(new Button.ClickListener() {
	@Override
	public void buttonClick(ClickEvent event) {
		checkBox.setValue(null);
	}
});
hl.addComponent(indeterminateButton);

hl.addComponent(checkBox);
```
